# Generated by Django 4.1.1 on 2022-09-15 05:55

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
