# Generated by Django 4.1.1 on 2022-09-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "price_per_night",
                    models.PositiveIntegerField(help_text="양수만 입력", verbose_name="요금"),
                ),
                ("address", models.CharField(max_length=140)),
                ("description", models.TextField()),
                (
                    "pets_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="이 집이 애완동물을 허가하는가?",
                        verbose_name="애완동물 가능",
                    ),
                ),
            ],
        ),
    ]
