# Generated by Django 4.1.1 on 2022-09-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "여러 카테고리"},
        ),
    ]
